### ISSUE TITLE
[Bug]: i face a problem when reinstalling venv 

### ISSUE THREAD

**Issue by waldolin** [lshqqytiger/stable-diffusion-webui-amdgpu#458]
### Checklist

- [X] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

i find you have [forge](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge)
so i git it 
PS D:\Users\lin\stable-diffusion-webui-directml> git remote add forge https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge
PS D:\Users\lin\stable-diffusion-webui-directml> git branch lshqqytiger/main
PS D:\Users\lin\stable-diffusion-webui-directml> git checkout lshqqytiger/main
Switched to branch 'lshqqytiger/main'
M       webui-user.bat
PS D:\Users\lin\stable-diffusion-webui-directml> git fetch forge
remote: Enumerating objects: 6709, done.
remote: Counting objects: 100% (2088/2088), done.
remote: Compressing objects: 100% (671/671), done.
remote: Total 6709 (delta 1500), reused 1802 (delta 1372), pack-reused 4621Receiving objects: 100% (6709/6709), 10.36 MiReceiving objects: 100% (6709/6709), 11.41 MiB | 2.38 MiB/s, done.

Resolving deltas: 100% (3613/3613), completed with 76 local objects.
From https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge
 * [new branch]        main       -> forge/main
PS D:\Users\lin\stable-diffusion-webui-directml> git pull
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (208/208), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 328 (delta 170), reused 203 (delta 167), pack-reused 120Receiving objects:  97% (319/328)
Receiving objects: 100% (328/328), 161.08 KiB | 695.00 KiB/s, done.
Resolving deltas: 100% (211/211), completed with 42 local objects.
From https://github.com/lshqqytiger/stable-diffusion-webui-directml
   17431009..88c12241  master     -> origin/master
 * [new tag]           v1.9.3-amd -> v1.9.3-amd
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> lshqqytiger/main

PS D:\Users\lin\stable-diffusion-webui-directml> git checkout master
Switched to branch 'master'
D       webui-user.bat
Your branch is behind 'origin/master' by 79 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
PS D:\Users\lin\stable-diffusion-webui-directml> cd extensions/sd-webui-animatediff
PS D:\Users\lin\stable-diffusion-webui-directml\extensions\sd-webui-animatediff> git checkout forge/master
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 12 (delta 0), reused 1 (delta 0), pack-reused 0Receiving objects:  83% (10/12)
Receiving objects: 100% (12/12), 31.26 KiB | 681.00 KiB/s, done.
Switched to a new branch 'forge/master'
branch 'forge/master' set up to track 'origin/forge/master'.
PS D:\Users\lin\stable-diffusion-webui-directml\extensions\sd-webui-animatediff> git pull
Already up to date.

 i face a problem when reinstalling venv 
Creating venv in directory D:\Users\lin\stable-diffusion-webui-directml\venv using python "C:\Users\lin\stable-diffusion-webui-directml\python\python.exe"
venv "D:\Users\lin\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Version: v1.9.0
Commit hash: 174310096385aa33d7b174f231650a941d73f19b
Installing torch and torchvision
Collecting torch==2.0.0
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Collecting torch-directml
  Using cached torch_directml-0.2.0.dev230426-cp310-cp310-win_amd64.whl (8.2 MB)
Collecting networkx
  Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Collecting filelock
  Downloading filelock-3.14.0-py3-none-any.whl (12 kB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting jinja2
  Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.3/133.3 kB 872.6 kB/s eta 0:00:00
Collecting numpy
  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached pillow-10.3.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.7-py3-none-any.whl (66 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torch-directml
Successfully installed MarkupSafe-2.1.5 certifi-2024.2.2 charset-normalizer-3.3.2 filelock-3.14.0 idna-3.7 jinja2-3.1.4 mpmath-1.3.0 networkx-3.3 numpy-1.26.4 pillow-10.3.0 requests-2.31.0 sympy-1.12 torch-2.0.0 torch-directml-0.2.0.dev230426 torchvision-0.15.1 typing-extensions-4.11.0 urllib3-2.2.1
WARNING: There was an error checking the latest version of pip.
Installing clip
Installing open_clip
Installing requirements
Installing onnxruntime-directml
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
D:\Users\lin\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --reinstall-torch --use-directml --medvram --precision full --no-half --no-half-vae --opt-sub-quad-attention --enable-insecure-extension-access --deepdanbooru --disable-nan-check
DirectML initialization failed: DLL load failed while importing torch_directml_native: 找不到指定的程序。

------------------------------------------------------------------------------------------------------------------------
launch.py 48 <module>
main()

launch.py 44 main
start()

launch_utils.py 696 start
import webui

webui.py 13 <module>
initialize.imports()

initialize.py 36 imports
shared_init.initialize()

shared_init.py 30 initialize
directml_do_hijack()

__init__.py 76 directml_do_hijack
if not torch.dml.has_float64_support(device):

__init__.py 2003 __getattr__
raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

AttributeError:
module 'torch' has no attribute 'dml'
請按任意鍵繼續 . . .

### Steps to reproduce the problem

1.git forge
2.reinstall venv

### What should have happened?

install success, and open it 

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

none

### Console logs

```Shell
as above
```

### Additional information

I have updated my GPU driver recently.

**Comment by lshqqytiger** [comment]
You should replace `--use-directml` with `--directml` on forge fork.

**Comment by waldolin** [comment]
> 您應該更換`--use-directml`為`--directml`鍛造前叉。

thank you a million.
is that means?
--use-directml  for directml
--directml for forge
