### ISSUE TITLE
[Bug]:  AttributeError: module 'diffusers.schedulers' has no attribute 'scheduling_lcm'

### ISSUE THREAD

**Issue by Ael07** [lshqqytiger/stable-diffusion-webui-amdgpu#461]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I deleted the Venv file and did a Git pull for the last version, all went well but the launch of the webui breaks at the last step;

I'm also using directml version with AMD GPU ... it was working well before one of the updates....

C:\Users\~\stable-diffusion-webui-directml>git pull
Already up to date.
venv "C:\Users\~\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.3-amd-11-g88c12241
Commit hash: 88c122412fb198ea8a5112c8a276ca1c33090caf
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\~\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --medvram --use-directml --no-half --precision full --opt-sub-quad-attention --opt-split-attention-v1 --theme dark --autolaunch --disable-safe-unpickle --disable-nan-check --skip-torch-cuda-test

------------------------------------------------------------------------------------------------------------------------
launch.py 48 <module>
main()

launch.py 44 main
start()

launch_utils.py 695 start
import webui

webui.py 13 <module>
initialize.imports()

initialize.py 36 imports
shared_init.initialize()

shared_init.py 30 initialize
directml_do_hijack()

__init__.py 69 directml_do_hijack
import modules.dml.hijack # noqa: F401

__init__.py 4 <module>
import modules.dml.hijack.diffusers

diffusers.py 189 <module>
) -> Union[diffusers.schedulers.scheduling_lcm.LCMSchedulerOutput, Tuple]:

AttributeError:
module 'diffusers.schedulers' has no attribute 'scheduling_lcm'
Press any key to continue . . .

### Steps to reproduce the problem

1 delete venv file
2 launch webui user bat file with git pull for last version
3 breaks at the launch of the webui

### What should have happened?

launch of a working webui

### Sysinfo

[sysinfo-2024-05-12-20-46.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/15287630/sysinfo-2024-05-12-20-46.json)

### Console logs

```Shell
C:\Users\~\stable-diffusion-webui-directml>git pull
Already up to date.
venv "C:\Users\~\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.3-amd-11-g88c12241
Commit hash: 88c122412fb198ea8a5112c8a276ca1c33090caf
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\~\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --medvram --use-directml --no-half --precision full --opt-sub-quad-attention --opt-split-attention-v1 --theme dark --autolaunch --disable-safe-unpickle --disable-nan-check --skip-torch-cuda-test

------------------------------------------------------------------------------------------------------------------------
launch.py 48 <module>
main()

launch.py 44 main
start()

launch_utils.py 695 start
import webui

webui.py 13 <module>
initialize.imports()

initialize.py 36 imports
shared_init.initialize()

shared_init.py 30 initialize
directml_do_hijack()

__init__.py 69 directml_do_hijack
import modules.dml.hijack # noqa: F401

__init__.py 4 <module>
import modules.dml.hijack.diffusers

diffusers.py 189 <module>
) -> Union[diffusers.schedulers.scheduling_lcm.LCMSchedulerOutput, Tuple]:

AttributeError:
module 'diffusers.schedulers' has no attribute 'scheduling_lcm'
Press any key to continue . . .
```

**Comment by Ael07** [comment]
I re installed directml stable diffusion, it is working perfectly on CPU but not GPU, issue reported

**Comment by oscartorres9** [comment]
same issue，after update latest code by git pull.
