### ISSUE TITLE
[Bug]: WebUI not launching, console output stops after applying optimization

### ISSUE THREAD

**Issue by popsoda27** [lshqqytiger/stable-diffusion-webui-amdgpu#470]
### Checklist

- [X] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Did not use for a week. Did a git pull when trying to work on it but already up to date. However, UI doesn't launch at all.
Autolaunch cmd arg is present. Tried --disable-all-extensions to no success.

### Steps to reproduce the problem

Did a git pull, no new updates.
Launch webui-user.bat
Console output to loading optimization stage and stays there.

### What should have happened?

WebUI should launch successfully as normal.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-05-28-18-42.json](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/files/15474559/sysinfo-2024-05-28-18-42.json)

### Console logs

```Shell
venv "E:\Downloads\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.3-amd-13-g517aaaff
Commit hash: 517aaaff2bb1a512057d88b0284193b9f23c0b47
Using ZLUDA in E:\Downloads\stable-diffusion-webui-directml\.zluda
Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\adetailer':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\sd-dynamic-prompts':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-aspect-ratio-helper':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-controlnet':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-deepdanbooru-object-recognition':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-infinite-image-browsing':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-lora-block-weight':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-loractl':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-prompt-all-in-one':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\Stable-Diffusion-Webui-Civitai-Helper':
Already up to date.

Pulled changes for repository in 'E:\Downloads\stable-diffusion-webui-directml\extensions\ultimate-upscale-for-automatic1111':
Already up to date.

no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --update-all-extensions --use-zluda --medvram --sub-quad-q-chunk-size 1024 --sub-quad-kv-chunk-size 256 --sub-quad-chunk-threshold 75 --autolaunch --no-half --precision full --skip-torch-cuda-test
ONNX: version=1.18.0 provider=CUDAExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
CHv1.8.8: Get Custom Model Folder
[-] ADetailer initialized. version: 24.5.1, num models: 13
ControlNet preprocessor location: E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\downloads
2024-05-29 02:44:14,750 - ControlNet - INFO - ControlNet v1.1.449
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [a49a581e95] from E:\Downloads\stable-diffusion-webui-directml\models\Stable-diffusion\t3_CivitaiVer15Beta.safetensors
CHv1.8.8: Set Proxy:
2024-05-29 02:44:15,274 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: E:\Downloads\stable-diffusion-webui-directml\configs\v1-inference.yaml
E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IIB Database file has been successfully backed up to the backup folder.
Startup time: 22.7s (prepare environment: 24.0s, initialize shared: 1.4s, load scripts: 1.8s, create ui: 0.5s, gradio launch: 1.0s, app_started_callback: 1.1s).
Loading VAE weights specified in settings: E:\Downloads\stable-diffusion-webui-directml\models\VAE\vaeFtMse840000EmaPruned_vae.safetensors
Applying attention optimization: Doggettx... done.
Model loaded in 4.1s (load weights from disk: 0.4s, create model: 0.6s, apply weights to model: 1.8s, apply float(): 0.2s, load VAE: 0.4s, calculate empty prompt: 0.6s).
```

**Comment by CS1o** [comment]
Whats your GPU?
It seems like your using Zluda but with many not needed launch arguments.
First remove `--sub-quad-q-chunk-size 1024 --sub-quad-kv-chunk-size 256 --sub-quad-chunk-threshold 75 --no-half --precision full --skip-torch-cuda-test`
If your GPU has 8GB VRAM (not RAM) you can change `--medvram` to `--medvram-sdxl`
with more than 12gb you can remove `--medvram-sdxl`
With these settings the Webui should work much faster.

You dont have any other errors in your cmd.
The Zluda Webui can take 15-40 minutes to load, mostly that happens after doing a GPU Driver update.
In your case, relaunch the webui-user.bat and just let it load. It will take a while but it will launch.
I had this case a few times before too. Its just like the first Zluda image generation.

**Comment by popsoda27** [comment]
> Whats your GPU? It seems like your using Zluda but with many not needed launch arguments. First remove `--sub-quad-q-chunk-size 1024 --sub-quad-kv-chunk-size 256 --sub-quad-chunk-threshold 75 --no-half --precision full --skip-torch-cuda-test` If your GPU has 8GB VRAM (not RAM) you can change `--medvram` to `--medvram-sdxl` with more than 12gb you can remove `--medvram-sdxl` With these settings the Webui should work much faster.
> 
> You dont have any other errors in your cmd. The Zluda Webui can take 15-40 minutes to load, mostly that happens after doing a GPU Driver update. In your case, relaunch the webui-user.bat and just let it load. It will take a while but it will launch. I had this case a few times before too. Its just like the first Zluda image generation. You also can open up the Webui manually with this URL: http://127.0.0.1:7860

Thank you very much for advice. This is resolved.

I'm on a 7900xtx and 5800X3D, last gpu update on 8th May and it's the latest.
With the current cmd args, it was working perfectly fine the week before I was away. Technically nothing changed because when I did the gitpull, there wasn't any updates to the UI. The args are based on user recommendations here on what worked so I'm not really sure exactly which args are necessary or not.

'The Zluda Webui can take 15-40 minutes to load,' I did not know it's ever that long. Usually it launches within a min.

However I tried launching with just '--update-all-extensions --use-zluda --autolaunch' and finally it pops up. Awesome.
