### ISSUE TITLE
[Bug]: No module named 'requests'

### ISSUE THREAD

**Issue by CS1o** [lshqqytiger/stable-diffusion-webui-amdgpu#482]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After the latest commit a few hours ago:
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/commit/9585f5dd5846e6a22f4386dfd415b831809bb64a
A clean webui installation with Zluda fails.

### Steps to reproduce the problem

Install python 3.10.11 64bit
Run pip cache purge in cmd
Git clone the repo.
launch the webui-user.bat with --use-zluda --medvram-sdxl --update-check --skip-ort

### What should have happened?

Normal installation process.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

Windows 10 64bit
AMD Radeon 7900XTX
Adrenalin 24.6.1

### Console logs

```Shell
Already up to date.
venv "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.9.3-amd-27-g9585f5dd
Commit hash: 9585f5dd5846e6a22f4386dfd415b831809bb64a
Traceback (most recent call last):
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\launch.py", line 48, in <module>
    main()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\launch.py", line 39, in main
    prepare_environment()
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 568, in prepare_environment
    from modules import zluda_installer
  File "D:\Programme\AI-Zeug\TEST\stable-diffusion-webui-amdgpu\modules\zluda_installer.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Drücken Sie eine beliebige Taste . . .
```

### Temporary Workaround (Fix):
go into the stable-diffusion-webui-amdgpu folder
click in the explorer adress bar (not searchbar)
type `cmd` and hit enter
copy and paste the following commands one by one:
`venv\Scripts\activate.bat`
`pip install requests`
Then relaunch the webui-user.bat

**Comment by lshqqytiger** [comment]
Fixed
