### ISSUE TITLE
Run vae on CPU to reduce vram usage

### ISSUE THREAD

**Issue by xhy2008** [lshqqytiger/stable-diffusion-webui-amdgpu#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I noticed that the vram usage keeps about 50% during generation,but out of memory when performing vae decoding.
So I suggest you could add an commandline arg to make the vae run on cpu so that I will not get out of memory errors after the last step of the generation with my 4GB card.😂

### Proposed workflow

1. Add an arg in webui-user.bat
2. After the generation the lantent will be sent to cpu and complete the vae decoding there.
3. No out of memory errors anymore!😃Maybe increase max image size to 768*768 on my device.

**Comment by lshqqytiger** [comment]
Have you tried `--lowvram`?

**Comment by xhy2008** [comment]
yes, I can't even generate an image without --lowvram.
I compared the time used from the last step over to the image is showed in the webui,pure cpu  inference is much slower than directml,so I thought the vae is running on directml device even if I passed --lowvram.

**Comment by xhy2008** [comment]
It is driving me mad.I always get "Out of Memory" even after the last step.
It seems there is not enough vram for the vae decoding.So I want to run only vae on cpu.

Output:

Reusing loaded model anythingV5-inpainting-pruned.safetensors to load darkSushiMixMix_225D.safetensors
Loading weights [None] from F:\stable-diffusion-webui-directml\models\Stable-diffusion\darkSushiMixMix_225D.safetensors
Creating model from config: F:\stable-diffusion-webui-directml\configs\v1-inference.yaml
F:\venv\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Applying attention optimization: Doggettx... done.
Model loaded in 19.2s (create model: 0.9s, apply weights to model: 16.2s, apply half(): 0.2s, apply dtype to VAE: 0.2s, load weights from state dict: 0.1s, hijack: 0.2s, load textual inversion embeddings: 0.5s, calculate empty prompt: 0.7s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [05:24<00:00, 16.21s/it]
*** Error completing request
*** Arguments: ('task(wird4p515gvo2tq)', <gradio.routes.Request object at 0x000002957EBD29E0>, 0, '<lora:mecha_20230530090512:0.8><lora:mechaangelv2-noise:0.2>1girl,angel_armor,angel_mecha,flying,angel_wings,angel_sword,weapon,long_hair,mecha,full_body', 'NG_DeepNegative_V1_75T,lowres,((bad_anatomy)),((bad_hands)),((text)),error,((missing_fingers)),((extra_digit)),((fewer_digits)),cropped,worst_quality,low_quality,normal_quality,jpeg_artifacts,signature,watermark, username,blurry,simple_background,no_nose,black_white,blood', [], <PIL.Image.Image image mode=RGBA size=512x768 at 0x295125ED690>, None, None, None, None, None, None, 4, 0, 1, 1, 1, 7.5, 1.5, 0.35, 0.0, 768, 512, 1, 3, 0, 32, 0, '', '', '', [], False, [], '', 0, False, 1, 0.5, 4, 0, 0.5, 2, 20, 'Euler', 'Automatic', False, '', 0.8, -1, False, -1, 0, 0, 0, 0, 0, 0, 0, 0.25, False, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_model_classes': '', 'ad_tab_enable': True, 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False, 'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'DPM++ 2M', 'ad_scheduler': 'Use same scheduler', 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False, 'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': ()}, ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.UNKNOWN: 'Unknown'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.UNKNOWN: 'Unknown'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.UNKNOWN: 'Unknown'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), ControlNetUnit(is_ui=True, input_mode=<InputMode.SIMPLE: 'simple'>, batch_images='', output_dir='', loopback=False, enabled=False, module='none', model='None', weight=1.0, image=None, resize_mode=<ResizeMode.INNER_FIT: 'Crop and Resize'>, low_vram=False, processor_res=-1, threshold_a=-1.0, threshold_b=-1.0, guidance_start=0.0, guidance_end=1.0, pixel_perfect=False, control_mode=<ControlMode.BALANCED: 'Balanced'>, inpaint_crop_input_image=False, hr_option=<HiResFixOption.BOTH: 'Both'>, save_detected_map=True, advanced_weighting=None, effective_region_mask=None, pulid_mode=<PuLIDMode.FIDELITY: 'Fidelity'>, union_control_type=<ControlNetUnionControlType.UNKNOWN: 'Unknown'>, ipadapter_input=None, mask=None, batch_mask_dir=None, animatediff_batch=False, batch_modifiers=[], batch_image_files=[], batch_keyframe_idx=None), False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, 'start', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, None, None, False, 50, '', 2, True, 'Wavelet', False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\stable-diffusion-webui-directml\modules\img2img.py", line 232, in img2img
        processed = process_images(p)
      File "F:\stable-diffusion-webui-directml\modules\processing.py", line 847, in process_images
        res = process_images_inner(p)
      File "F:\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 59, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "F:\stable-diffusion-webui-directml\modules\processing.py", line 1087, in process_images_inner
        x_samples_ddim = decode_latent_batch(p.sd_model, samples_ddim, target_device=devices.cpu, check_for_nans=True)
      File "F:\stable-diffusion-webui-directml\modules\processing.py", line 634, in decode_latent_batch
        sample = decode_first_stage(model, batch[i:i + 1])[0]
      File "F:\stable-diffusion-webui-directml\modules\sd_samplers_common.py", line 76, in decode_first_stage
        return samples_to_images_tensor(x, approx_index, model)
      File "F:\stable-diffusion-webui-directml\modules\sd_samplers_common.py", line 58, in samples_to_images_tensor
        x_sample = model.decode_first_stage(sample.to(model.first_stage_model.dtype))
      File "F:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 18, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "F:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 32, in __call__
        return self.__orig_func(*args, **kwargs)
      File "F:\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "F:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
        return self.first_stage_model.decode(z)
      File "F:\stable-diffusion-webui-directml\modules\lowvram.py", line 71, in first_stage_model_decode_wrap
        return first_stage_model_decode(z)
      File "F:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
        dec = self.decoder(z)
      File "F:\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 637, in forward
        h = self.up[i_level].block[i_block](h, temb)
      File "F:\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "F:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 139, in forward
        h = nonlinearity(h)
      File "F:\venv\lib\site-packages\torch\nn\functional.py", line 2059, in silu
        return torch._C._nn.silu(input)
    RuntimeError: Could not allocate tensor with 100663296 bytes. There is not enough GPU video memory available!

---

**Comment by ananosleep** [comment]
Did you try this [extension](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111)?
enable Tiled VAE only is enough

**Comment by xhy2008** [comment]
I tried many times,but it raised RuntimeError every time,seems that a nans is produced in the vae decoder.![IMG_20240726_163441.jpg](https://github.com/user-attachments/assets/f6acc9ed-f480-4cb8-ae68-6094c6563271)

**Comment by xhy2008** [comment]
I don't mind how slow it is,because I am running comfyui on cpu only.(comfyui don't support lowvram on directml devices)

**Comment by CS1o** [comment]
First make sure your webui is updated to the latest version. (1.10)
Then check that your webui-user.bat only has:
`--use-directml --lowvram --opt-sub-quad-attention --opt-split-attention --no-half-vae --upcast-sampling`
in the Commandline_Args.
No chunk allocation stuff lines etc.
Then also only enable Tiled VAE.

Then try to generate an image in txt2img with the following settings:
Model: 1.5 based preferable 2gb in size.
Resolution: 512x512
CFG: 7
Steps: 30
Prompt: Cat
Negative prompt: Blurry

If that works try to generate a 768x768.

Dont enable Hires Fix. It wont work with 4gb vram. For upscaling you only can use the SD-Upscale Script in the img2img tab.
Dont use "Resize to" in img2img.

Let me if it worked.
If you get an error again please share the complete cmd log and an screenshot of your txt2img settings.

**Comment by ananosleep** [comment]
Tiled VAE will still produce grey tile at the bottom left... like this:
![00002-2306472887](https://github.com/user-attachments/assets/c6b4a89d-97d6-4b79-8166-0cbc1e4f9728)
Microsoft had 3 updates this year, but this bug is still not fixed...

**Comment by ananosleep** [comment]
I have a method that could run vae on cpu, maybe you can try it when tiled vae can't work properly.
Note: it only works with `--lowvram --no-half-vae`

1. `git pull` to make sure you're at latest version, now it's at 395ce8dc2cb01282d48074a89a5e6cb3da4b59ab
2. Find these two files: `modules\processing.py` and `modules\lowvram.py`
3. Copy them to another place as backup
4. edit them as below: 

processing.py: add after line 1082
samples_ddim = samples_ddim.to(devices.dtype_vae).to("cpu") 
x_samples_ddim = decode_first_stage(p.sd_model, samples_ddim) 
![image](https://github.com/user-attachments/assets/627d77ba-4592-447d-84de-838f65519ddd)

lowvram.py: add a `#` at line 73:
![image](https://github.com/user-attachments/assets/ecae85ea-194e-4d73-9ca8-d47336027a4b)

Now vae will run on cpu. (Note: extremely slow! )
Only test on sd1.5 because I only have a 2GB AMD Radeon Pro WX2100 which can't run sdxl.

By the way, if you don't mind a little quality lost, maybe you can try using TAESD. Enable it at `settings->VAE`

**Comment by CS1o** [comment]
> Tiled VAE will still produce grey tile at the bottom left... like this: !

@ananosleep 
Not using the right Encoder/Decoder Resolution, or a uncommon Image Resolution will result in gray sqaures in the Image.
So if using 1.5 based models, set it to Encoder: 1024, Decoder: 128
You can also try Encoder: 768, Decoder: 128

For SDXL Users, set "Upscale by" to 1.5, Resolution to 768x1024 and the Encoder: 1280, Decoder: 128 to not get gray squares with DirectML + TiledVAE.

**Comment by ananosleep** [comment]
> > Tiled VAE will still produce grey tile at the bottom left... like this: !
> 
> @ananosleep Not using the right Encoder/Decoder Resolution, or a uncommon Image Resolution will result in gray sqaures in the Image. So if using 1.5 based models, set it to Encoder: 1024, Decoder: 128 You can also try Encoder: 768, Decoder: 128
> 
> For SDXL Users, set "Upscale by" to 1.5, Resolution to 768x1024 and the Encoder: 1280, Decoder: 128 to not get gray squares with DirectML + TiledVAE.

@CS1o 
I tried this with sd1.5, 576x1024 without hires fix but got OOM...2gb vram is toooo small. 
But encoder 512 and decoder 64 works well. After all, thanks for your advice
