### ISSUE TITLE
[Bug]: Training Embeding

### ISSUE THREAD

**Issue by VeteranXT** [lshqqytiger/stable-diffusion-webui-amdgpu#498]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

Trying to make train embeding. Stuck at preparing dataset.
Never started 

### Steps to reproduce the problem

1. Create Embeding
2. Select Created Embeding
3. Add Dataset path
4. Train Embeding

### What should have happened?

Started Training,

### Sysinfo

[sysinfo-2024-07-31-19-56.json](https://github.com/user-attachments/files/16446596/sysinfo-2024-07-31-19-56.json)

### Console logs

```Preparing dataset...
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:07<00:00,  3.35it/s]
  0%|                                                                                       | 0/100000 [00:00<?, ?it/s] 
```

**Comment by CS1o** [comment]
Hey, in your sysinfo it states that your using amdgpu-forge webui so this would be the wrong repo to create the issue in.

But its also strange that you have --use-zluda in the webui-user.bat because for the forge webui it should have been --zluda
Also remove --disable-safe-unpickle (its a not needed security risk)

If you want to train something i would recommend using OneTrainer. Its an external Tool for training loras or models and supports Zluda.

**Comment by VeteranXT** [comment]
I tried AMD FORGE, AMD, FORGE and SD.Next none could train. It would throw error. 
--disable-safe-unpickle  was error that asked to do that so i ended on that.

**Comment by VeteranXT** [comment]
I still can't train inside of AMDGPU. i have both repos. I'll update Logs

**Comment by CS1o** [comment]
Yea its not possible to train with the webuis. Thats why i suggested OneTrainer. Its the only capable tool for that for AMD Users.

Also AMD-Forge uses --zluda like seen on the repo site:
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu-forge
![grafik](https://github.com/user-attachments/assets/3af9c396-d71b-4999-815d-df09921b7388)

**Comment by VeteranXT** [comment]
I can't get captions to work on OneTrainer. Can't get text files to generate.
