### ISSUE TITLE
[Bug]: error code 1

### ISSUE THREAD

**Issue by DELTER1235** [lshqqytiger/stable-diffusion-webui-amdgpu#504]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Hello, when I tried to download stable diffusion, when opening a bat file, after a while an error with code 1 appears

### Steps to reproduce the problem

Download blank file using cmd
Run the bat file by double-clicking the left mouse button

### What should have happened?

Everything should be installed after opening the bat file, and then a link to the stable diffusion site will appear

### What browsers do you use to access the UI ?

Google Chrome, Microsoft Edge

### Sysinfo

[sysinfo.txt](https://github.com/user-attachments/files/16403918/sysinfo.txt)

### Console logs

```Shell
venv "E:\stable diffusion\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1-amd-2-g395ce8dc
Commit hash: 395ce8dc2cb01282d48074a89a5e6cb3da4b59ab
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting torch==2.3.0
  Using cached https://download.pytorch.org/whl/cu121/torch-2.3.0%2Bcu121-cp310-cp310-win_amd64.whl (2413.3 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu121/torchvision-0.19.0%2Bcu121-cp310-cp310-win_amd64.whl (5.8 MB)
Collecting filelock (from torch==2.3.0)
  Using cached filelock-3.15.4-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions>=4.8.0 (from torch==2.3.0)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch==2.3.0)
  Using cached sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.3.0)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting jinja2 (from torch==2.3.0)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch==2.3.0)
  Using cached fsspec-2024.6.1-py3-none-any.whl.metadata (11 kB)
Collecting mkl<=2021.4.0,>=2021.1.1 (from torch==2.3.0)
  Using cached https://download.pytorch.org/whl/mkl-2021.4.0-py2.py3-none-win_amd64.whl (228.5 MB)
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

Traceback (most recent call last):
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\launch.py", line 48, in <module>
    main()
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\launch.py", line 39, in main
    prepare_environment()
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 559, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 120, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "E:\stable diffusion\stable-diffusion-webui-amdgpu\venv\Scripts\python.exe" -m pip install torch==2.3.0 torchvision --extra-index-url https://download.pytorch.org/whl/cu121
Error code: 1
Для продолжения нажмите любую клавишу . . .
```

### Additional information

components of my PC: video card: radeon rx560 series, processor: Amd ryzen 3 1200 Quad-Core Processor

**Comment by lshqqytiger** [comment]
No disk space left.
```[Errno 28] No space left on device```

**Comment by DELTER1235** [comment]
> No disk space left. `[Errno 28] No space left on device`

This is strange, on the disk on which stable diffusion is installed there is another 100 gigabytes of space

**Comment by DELTER1235** [comment]
> No disk space left. `[Errno 28] No space left on device`

я очистил память на всех дисках и теперь у меня эта проблема

venv "E:\stable diffusion\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1-amd-2-g395ce8dc
Commit hash: 395ce8dc2cb01282d48074a89a5e6cb3da4b59ab
Installing clip
Installing open_clip
Cloning assets into E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-webui-assets...
Cloning into 'E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-webui-assets'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20 (delta 0), reused 20 (delta 0), pack-reused 0
Receiving objects: 100% (20/20), 132.70 KiB | 497.00 KiB/s, done.
Cloning Stable Diffusion into E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai...
Cloning into 'E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\stable-diffusion-stability-ai'...
remote: Enumerating objects: 580, done.
remote: Counting objects: 100% (571/571), done.
remote: Compressing objects: 100% (306/306), done.
remote: Total 580 (delta 278), reused 446 (delta 247), pack-reused 9
Receiving objects: 100% (580/580), 73.44 MiB | 11.23 MiB/s, done.
Resolving deltas: 100% (278/278), done.
Updating files: 100% (135/135), done.
Cloning Stable Diffusion XL into E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\generative-models...
Cloning into 'E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\generative-models'...
remote: Enumerating objects: 983, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 983 (delta 8), reused 31 (delta 7), pack-reused 941
Receiving objects: 100% (983/983), 52.06 MiB | 13.65 MiB/s, done.
Resolving deltas: 100% (497/497), done.
Updating files: 100% (130/130), done.
Cloning K-diffusion into E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\k-diffusion...
Cloning into 'E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\k-diffusion'...
remote: Enumerating objects: 1345, done.
remote: Counting objects: 100% (1345/1345), done.
remote: Compressing objects: 100% (443/443), done.
remote: Total 1345 (delta 947), reused 1249 (delta 895), pack-reused 0
Receiving objects: 100% (1345/1345), 232.84 KiB | 857.00 KiB/s, done.
Resolving deltas: 100% (947/947), done.
Cloning BLIP into E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\BLIP...
Cloning into 'E:\stable diffusion\stable-diffusion-webui-amdgpu\repositories\BLIP'...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 277 (delta 137), reused 136 (delta 135), pack-reused 112
Receiving objects: 100% (277/277), 7.03 MiB | 7.95 MiB/s, done.
Resolving deltas: 100% (152/152), done.
Installing requirements
Installing onnxruntime-gpu
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
E:\stable diffusion\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --skip-torch-cuda-test
Traceback (most recent call last):
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\launch.py", line 48, in <module>
    main()
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\launch.py", line 44, in main
    start()
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 686, in start
    import webui
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\webui.py", line 13, in <module>
    initialize.imports()
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\modules\initialize.py", line 35, in imports
    from modules import shared_init
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\modules\shared_init.py", line 8, in <module>
    from modules.zluda import initialize_zluda
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\modules\zluda.py", line 5, in <module>
    import onnxruntime as ort
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\venv\lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\venv\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "E:\stable diffusion\stable-diffusion-webui-amdgpu\venv\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError: DLL load failed while importing onnxruntime_pybind11_state: Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL).
Для продолжения нажмите любую клавишу . . .

**Comment by lshqqytiger** [comment]
Try this:
```
.\venv\Scripts\activate
pip uninstall onnxruntime onnxruntime-gpu -y
pip install onnxruntime
```
then run webui with `--skip-ort`

**Comment by DELTER1235** [comment]
> Try this:
> 
> ```
> .\venv\Scripts\activate
> pip uninstall onnxruntime onnxruntime-gpu -y
> pip install onnxruntime
> ```
> 
> then run webui with `--skip-ort`

Which "activate" file are we talking about? There is one with the extension bat, ps1 and just a file

**Comment by lshqqytiger** [comment]
`.bat` will be selected.

**Comment by DELTER1235** [comment]
> `.bat` will be selected.

It helped to launch the SD itself, but the images are not generated (the models are installed), below it says the following: RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same
