### ISSUE TITLE
RuntimeError: Couldn't install torch.  Error code: 1 PLEASE HELP

### ISSUE THREAD

**Issue by buatemai** [lshqqytiger/stable-diffusion-webui-amdgpu#513]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

i followed this tutorial completely https://www.youtube.com/watch?v=eO88i8o-BoY&t=551s&ab_channel=Northbound
until step where i open webui-user files but it give me this error

RuntimeError: Couldn't install torch.

### Steps to reproduce the problem

already using python 3.10.6
already install git 

### What should have happened?

gives error like RuntimeError: Couldn't install torch.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

web

### Console logs

```Shell
'"C:\Users\buate\Desktop\tutorial\stable-diffusion-webui-amdgpu\venv\Scripts\activate.bat"' is not recognized as an internal or external command,
operable program or batch file.
venv "C:\Users\buate\Desktop\tutorial\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1-amd-2-g395ce8dc
Commit hash: 395ce8dc2cb01282d48074a89a5e6cb3da4b59ab
Installing torch and torchvision 
C:\Users\buate\Desktop\tutorial\stable-diffusion-webui-amdgpu\venv\Scripts\python.exe: No module named pip
Traceback (most recent call last):
  File "C:\Users\buate\Desktop\tutorial\stable-diffusion-webui-amdgpu\launch.py", line 48, in <module>
    main()
  File "C:\Users\buate\Desktop\tutorial\stable-diffusion-webui-amdgpu\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\buate\Desktop\tutorial\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 559, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "C:\Users\buate\Desktop\tutorial\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 120, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "C:\Users\buate\Desktop\tutorial\stable-diffusion-webui-amdgpu\venv\Scripts\python.exe" -m pip install torch==2.3.1 torchvision torch-directml
Error code: 1
Press any key to continue . . .
```

### Additional information

any one can help please .

**Comment by CS1o** [comment]
Hey, idk whats your GPU, but if you have a card with 8gb vram or more you should use Zluda instead of DirectML.
Follow my AMD Automatic1111 with Zluda guide from here:
https://github.com/CS1o/Stable-Diffusion-Info/wiki/Installation-Guides
