### ISSUE TITLE
[Bug]: AMD Radeon RX 7900 XT gives Roc Blas error for gfx 1036 instead of 1100 

### ISSUE THREAD

**Issue by vivelaviet** [lshqqytiger/stable-diffusion-webui-amdgpu#520]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I'm using the 7900 XT but somehow I get a RocBlas error for gfx 1036 instead of gfx 1100 which should be what my GPU supports for some season. I can't override it with HSA_OVERRIDE_GFX_VERSION=11.0.0 because I think that is linux only so I'm at a loss on what to do. 

### Steps to reproduce the problem

I followed the steps here for ZLUDA for AMD on Winsows : https://github.com/CS1o/Stable-Diffusion-Info/wiki/Installation-Guides

### What should have happened?

WebUI should have just installed cleanly at this point.

### Sysinfo

venv "C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\launch.py", line 48, in <module>
    main()
  File "C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\launch.py", line 29, in main
    filename = launch_utils.dump_sysinfo()
  File "C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\modules\launch_utils.py", line 698, in dump_sysinfo
    text = sysinfo.get()
  File "C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\modules\sysinfo.py", line 46, in get
    res = get_dict()
  File "C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\modules\sysinfo.py", line 119, in get_dict
    "Extensions": get_extensions(enabled=True, fallback_disabled_extensions=config.get('disabled_extensions', [])),
AttributeError: 'str' object has no attribute 'get'
Press any key to continue . . .

### Console logs

```Shell
venv "C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1-amd-2-g395ce8dc
Commit hash: 395ce8dc2cb01282d48074a89a5e6cb3da4b59ab
Using ZLUDA in C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\.zluda
Skipping onnxruntime installation.
You are up to date with the most recent release.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\doomi\Documents\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda --update-check --skip-ort

rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.1\bin\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1036

rocBLAS error: Could not initialize Tensile host:
regex_error(error_backref): The expression contained an invalid back reference.
Press any key to continue . . .
```

### Additional information

GPU: AMD Radeon RX 7900 XT
OS: Windows 10

**Comment by lshqqytiger** [comment]
You can use only one card with ZLUDA at the same time.
To prevent iGPU from blocking discrete card to be used, please run webui with environment variable `HIP_VISIBLE_DEVICES`.
For example, `HIP_VISIBLE_DEVICES=1` will force ZLUDA to see `GPU 1`.

**Comment by vivelaviet** [comment]
Thanks it seems like that was the case
