### ISSUE TITLE
[Bug]: when trying to run the bat file an error occurs

### ISSUE THREAD

**Issue by DELTER1235** [lshqqytiger/stable-diffusion-webui-amdgpu#522]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

When I try to run the bat file this error pops up:
![image](https://github.com/user-attachments/assets/af903068-da4f-4fd2-81a6-55c6338518d3)

### Steps to reproduce the problem

download stable diffusion, python 3.10. and other files from the guide

### What should have happened?

Correct operation of stable diffusion

### Sysinfo

[sysinfo.txt](https://github.com/user-attachments/files/16610204/sysinfo.txt)

### Console logs

```Shell
""E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\venv\Scripts\activate.bat"" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
venv "E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\venv\Scripts\Python.exe"
Error processing line 1 of E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\sem34\AppData\Local\Programs\Python\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\sem34\AppData\Local\Programs\Python\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.10.1
Commit hash: <none>
Installing torch and torchvision
Error processing line 1 of E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\sem34\AppData\Local\Programs\Python\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Error processing line 1 of E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\venv\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\sem34\AppData\Local\Programs\Python\Python310\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\venv\Scripts\python.exe: No module named pip
Traceback (most recent call last):
  File "E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\launch.py", line 48, in <module>
    main()
  File "E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\launch.py", line 39, in main
    prepare_environment()
  File "E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\modules\launch_utils.py", line 559, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\modules\launch_utils.py", line 120, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master\venv\Scripts\python.exe" -m pip install torch==2.3.0 torchvision --extra-index-url https://download.pytorch.org/whl/cu121
Error code: 1
```

### Additional information  I noticed an interesting detail, on another disk stable diffusion starts up quietly and this error pops up only on an external hard drive, not allowing you to download anything from Github, but files from the Internet are still easily downloaded, I know that this is no longer an SD problem, but I want to ask, do you have any idea what this is connected with?

I solved this problem by simply reconnecting the hard drive

Error code 1 I can fix, but I don’t know what to do with a failed launch

**Comment by CS1o** [comment]
Hey, you installed it the wrong way.
Follow my AMD Automatic1111 with ZLUDA Guide if your GPU is supported. (Best performance)
If not follow the DirectML Guide.
The Guides can be found here:
https://github.com/CS1o/Stable-Diffusion-Info/wiki/Installation-Guides

**Comment by lshqqytiger** [comment]
It seems your Python or virtual environment is broken.
Please try
1. Remove venv and let the installer re-create it.
2. If the same problem still exists, reinstall Python.

**Comment by DELTER1235** [comment]
> It seems your Python or virtual environment is broken. Please try
> 
> 1. Remove venv and let the installer re-create it.
> 2. If the same problem still exists, reinstall Python.

I did both actions, when deleting venv the same thing happens, but in this window a message also appears that information about the components of the venv folder is lost, reinstalling python does not help, however, I noticed an interesting detail, on another disk stable diffusion starts up quietly and this error pops up only on an external hard drive, not allowing you to download anything from Github, but files from the Internet are still easily downloaded, I know that this is no longer an SD problem, but I want to ask, do you have any idea what this is connected with?

**Comment by DELTER1235** [comment]
> Hey, you installed it the wrong way. Follow my AMD Automatic1111 with ZLUDA Guide if your GPU is supported. (Best performance) If not follow the DirectML Guide. The Guides can be found here: https://github.com/CS1o/Stable-Diffusion-Info/wiki/Installation-Guides

Thank you for the advice, but I recently found out that the problem is not related to the Automatic1111 files

**Comment by CS1o** [comment]
> I did both actions, when deleting venv the same thing happens, but in this window a message also appears that information about the components of the venv folder is lost, reinstalling python does not help, however, I noticed an interesting detail, on another disk stable diffusion starts up quietly and this error pops up only on an external hard drive, not allowing you to download anything from Github, but files from the Internet are still easily downloaded, I know that this is no longer an SD problem, but I want to ask, do you have any idea what this is connected with?

That happens because you didn't installed the webui correctly using Git and the Git clone command.
Also moving the Webui to an external drive can cause Permission errors and breaks webui updates.

Thats also why it says Commit hash: none
Also you installed the webuiwebui twice and inside itself.
Your folder path is called:
"E:\stabily diff\stable-diffusion-webui-amdgpu\stable-diffusion-webui-amdgpu-master

Thats not good. Delete the stable-diffusion-webui-amdgpu-master folder as downloading as zip is the wrong way for install.
Then delete the venv folder of
"E:\stabily diff\stable-diffusion-webui-amdgpu"
Then open up a cmd and type
Pip cache purge
Finally launch the webui-user.bat with the right launch args.
That should fix everything.

If not delete everything and reinstall Python and then follow one of my Guides.
