### ISSUE TITLE
[Bug]: embedding files not showing up on textual inversion

### ISSUE THREAD

**Issue by Surya-733** [lshqqytiger/stable-diffusion-webui-amdgpu#525]
### Checklist

- [x] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [x] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

im adding a .pt file on embedding folder, but it wont show up or usable

### Steps to reproduce the problem

1. download an embedding .pt file
2. put the .pt file on embeddng folder
3. try to use the embedding on negative prompt

### What should have happened?

able to use the embedding file on negative prompt

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-08-19-17-10.json](https://github.com/user-attachments/files/16663336/sysinfo-2024-08-19-17-10.json)

### Console logs

```Shell
venv "C:\AI 2\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.1-amd-2-g395ce8dc
Commit hash: 395ce8dc2cb01282d48074a89a5e6cb3da4b59ab
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\AI 2\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-directml --lowvram --opt-sub-quad-attention --opt-split-attention --no-half-vae --upcast-sampling
ONNX failed to initialize: Failed to import diffusers.pipelines.auto_pipeline because of the following error (look up to see its traceback):
Failed to import diffusers.pipelines.aura_flow.pipeline_aura_flow because of the following error (look up to see its traceback):
cannot import name 'UMT5EncoderModel' from 'transformers' (C:\AI 2\stable-diffusion-webui-amdgpu\venv\lib\site-packages\transformers\__init__.py)
Loading weights [2b493af7c1] from C:\AI 2\stable-diffusion-webui-amdgpu\models\Stable-diffusion\tPonynai3_v6.safetensors
Creating model from config: C:\AI 2\stable-diffusion-webui-amdgpu\repositories\generative-models\configs\inference\sd_xl_base.yaml
C:\AI 2\stable-diffusion-webui-amdgpu\venv\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.6s (prepare environment: 9.0s, initialize shared: 0.9s, load scripts: 0.3s, create ui: 0.2s, gradio launch: 0.4s).
Applying attention optimization: Doggettx... done.
Model loaded in 6.2s (load weights from disk: 0.3s, create model: 0.6s, apply weights to model: 3.4s, calculate empty prompt: 1.7s).
Restarting UI...
Closing server running on port: 7860
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 0.6s (load scripts: 0.2s, create ui: 0.2s, gradio launch: 0.3s).
```

### Additional information

im using igpu 760m.
im very much new to any of this, thanks a lot if you help me.

**Comment by CS1o** [comment]
Make sure the embedding is compatible with sdxl models.
It wont work or show up when its not compatible.
1.5 embeddings need a 1.5 model and sdxl embeddings work only with sdxl models and pony.

**Comment by Surya-733** [comment]
> Make sure the embedding is compatible with sdxl models. It wont work or show up when its not compatible. 1.5 embeddings need a 1.5 model and sdxl embeddings work only with sdxl models and pony.

ohh thanks a lot, i didnt know or notice that, thanks a lot!
