### ISSUE TITLE
BINARIES!

### ISSUE THREAD

**Issue by jabcreations** [lshqqytiger/stable-diffusion-webui-amdgpu#532]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [X] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

Someone got lazy.

### Steps to reproduce the problem

1. Look for download.
2. See only "source code".
3. Do not accomplish goals.

### What should have happened?

I create software or write a fix for a problem for a website I upload the fix to the server.

You make software you release a binary.

### What browsers do you use to access the UI ?

Other

### Sysinfo

no

### Console logs

```Shell
no
```

### Additional information

1

**Comment by lshqqytiger** [comment]
Binaries are not provided. Please follow [README](https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/blob/master/README.md).
