### ISSUE TITLE
[Bug]: Memory issues and absurdly slow speed when upscaling an image on Windows 11, with AMD Radeon RX 6750 XT

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [lshqqytiger/stable-diffusion-webui-amdgpu#548]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

First of all, when installing webui for the first time, I had issues with launching it at all. Eventually, I managed to launch it with the following arguments:
`COMMANDLINE_ARGS= --use-directml --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1`
after browsing through issues of other people here.

Now, while the webui launches properly and allows me to generate images, it is absurdly irregular with its working speed (a 360x360 image from a text prompt generated in around 17 seconds while a single x2 upscale of the generated image took around 4 minutes). Not only that, but the webui consumes an insane amount of memory. The first image consumes around half of the dedicated GPU memory, while the upscale consumes nearly 100% of it.

Additionally, I want to note that while I was messing with the commandline arguments earlier, the webui did not want to upscale at all as it was constantly running out of memory, or it took an absurd 30 minutes to generate the upscaled image, which is something I don't believe should happen at all.

### Steps to reproduce the problem

1. Install a clean version of the webui.
2. Set the commandline arguments of webui-user.bat to `COMMANDLINE_ARGS= --use-directml --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1`.
3. Attempt to generate a 360x360 image from a text prompt, then attempt to upscale it to twice of its size.

### What should have happened?

The upscale shouldn't take as long to generate and it shouldn't consume almost 100% of the GPU's memory.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-10-17-12-18.json](https://github.com/user-attachments/files/17412292/sysinfo-2024-10-17-12-18.json)

### Console logs

```Shell
https://pastebin.com/raw/LvmNBEj6
```

**Comment by lshqqytiger** [comment]
--use-directml: DirectML is slower than ZLUDA.
--no-half --precision full --no-half-vae: Full precision (32-bit) is slower than half precision (16-bit)

Your card is capable to run ZLUDA and half precision. You are slowing down the generation by using arguments that are for older (pre-navi) cards.

**Comment by lshqqytiger** [comment]
Have you installed HIP SDK?

**Comment by BlindTheBoundDemon** [comment]
I have no idea what that is

**Comment by lshqqytiger** [comment]
Follow [this guide](https://github.com/vladmandic/automatic/wiki/ZLUDA). (expect for `Install SD.Next` section)

**Comment by BlindTheBoundDemon** [comment]
I tried and now i get this at the end of the terminal:
```Launching Web UI with arguments: --use-zluda
ONNX failed to initialize: module 'optimum.onnxruntime.modeling_diffusion' has no attribute '_ORTDiffusionModelPart'
Compiling in progress. Please wait...

rocBLAS error: Cannot read C:\Program Files\AMD\ROCm\6.1\bin\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1031

rocBLAS error: Could not initialize Tensile host:
regex_error(error_backref): The expression contained an invalid back reference.
Press any key to continue . . .```

**Comment by lshqqytiger** [comment]
Did you follow `Replace HIP SDK library files for unsupported GPU architectures` step?

**Comment by BlindTheBoundDemon** [comment]
yes

**Comment by lshqqytiger** [comment]
The rocmlibs you downloaded are built for HIP SDK 5.7, but you have HIP SDK 6.1, which is incompatible.
Search for 6.1 (on GitHub? Reddit? I've seen one in SD.Next Discord) or just downgrade HIP SDK to 5.7.

**Comment by BlindTheBoundDemon** [comment]
i see, is there a particular sequence of downgrading or do i just launch the installer for 5.7 and it will downgrade HIP SDK on its own?

**Comment by lshqqytiger** [comment]
I haven't downgraded HIP SDK at all. But I'd recommend to uninstall existing one and run installer.
As you replaced (and added) some files, wipe `path/to/AMD/ROCm` folder to prevent conflicts.

**Comment by BlindTheBoundDemon** [comment]
wait how do i uninstall the 6.1 one?

**Comment by lshqqytiger** [comment]
In control panel or settings like other programs. It is divided into some components. Uninstall all of them.

**Comment by BlindTheBoundDemon** [comment]
> You may have to modify environment variable `HIP_PATH` if the installer cannot handle it properly due to previous installation.

also, where do i modify this?

**Comment by lshqqytiger** [comment]
I'm not sure whether it will be a problem. Check envvar if webui crashes while finding ROCm.

**Comment by BlindTheBoundDemon** [comment]
i tried launching webui-user.bat and got this:
```venv "C:\Users\48880\stable-diffusion-webui-amdgpu\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1-amd-11-gefddd05e
Commit hash: efddd05e11d9cc5339a41192457e6ff8ad06ae00
Failed to load ZLUDA: Could not find module 'C:\Users\48880\stable-diffusion-webui-amdgpu\.zluda\nvcuda.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Using CPU-only torch
C:\Users\48880\stable-diffusion-webui-amdgpu\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\48880\stable-diffusion-webui-amdgpu\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
ONNX failed to initialize: module 'optimum.onnxruntime.modeling_diffusion' has no attribute '_ORTDiffusionModelPart'
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to C:\Users\48880\stable-diffusion-webui-amdgpu\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

loading stable diffusion model: FileNotFoundError
Traceback (most recent call last):
  File "C:\Users\48880\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\48880\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\48880\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\initialize.py", line 149, in load_model
    shared.sd_model  # noqa: B018
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\shared_items.py", line 190, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 693, in get_sd_model
    load_model()
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 788, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 234, in select_checkpoint
    raise FileNotFoundError(error_message)
FileNotFoundError: No checkpoints found. When searching for checkpoints, looked at:
 - file C:\Users\48880\stable-diffusion-webui-amdgpu\model.ckpt
 - directory C:\Users\48880\stable-diffusion-webui-amdgpu\models\Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.


Stable diffusion model failed to load
Applying attention optimization: InvokeAI... done.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 26.9s (prepare environment: 36.5s, initialize shared: 1.5s, other imports: 0.2s, list SD models: 0.5s, load scripts: 0.8s, create ui: 0.3s, gradio launch: 0.2s).
loading stable diffusion model: FileNotFoundError
Traceback (most recent call last):
  File "C:\Users\48880\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\48880\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\ui.py", line 1740, in <lambda>
    visible=shared.sd_model and shared.sd_model.cond_stage_key == "edit"
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\shared_items.py", line 190, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 693, in get_sd_model
    load_model()
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 788, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "C:\Users\48880\stable-diffusion-webui-amdgpu\modules\sd_models.py", line 234, in select_checkpoint
    raise FileNotFoundError(error_message)
FileNotFoundError: No checkpoints found. When searching for checkpoints, looked at:
 - file C:\Users\48880\stable-diffusion-webui-amdgpu\model.ckpt
 - directory C:\Users\48880\stable-diffusion-webui-amdgpu\models\Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.


Stable diffusion model failed to load```

**Comment by BlindTheBoundDemon** [comment]
> I'm not sure whether it will be a problem. Check envvar if webui fails to find ROCm.

What does this mean?

**Comment by lshqqytiger** [comment]
Does nvcuda.dll exists in this path? `C:\Users\48880\stable-diffusion-webui-amdgpu\.zluda\nvcuda.dll`

**Comment by BlindTheBoundDemon** [comment]
Yes

Can you reply to my previous question btw?

**Comment by lshqqytiger** [comment]
The easiest way to check environment variable is to print on console.
Using PowerShell:
![image](https://github.com/user-attachments/assets/543beb7b-6b14-4dff-b624-cc2c6d631c9e)
Using Command Prompt:
![image](https://github.com/user-attachments/assets/bcd4d002-6c07-42ca-8f7c-4907c5476500)
You should have 5.7 instead of 6.1.

**Comment by lshqqytiger** [comment]
Do you have visual studio C++ runtime?

**Comment by BlindTheBoundDemon** [comment]
I do

**Comment by lshqqytiger** [comment]
Remove .zluda folder and try again. Maybe zluda for ROCm 6.1 was downloaded before you reinstall 5.7.

**Comment by BlindTheBoundDemon** [comment]
Okay I've decided I'm gonna delete all of this and install webui from fresh... Here's what I did:
1. I installed the webui by running `git clone https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu.git` in cmd
2. I added the `--use-zluda` argument to webui-user.bat
3. I ran webui-user.bat
4. The UI opened in my browser but here's what the terminal has produced throughout the entire operation:
[log.txt](https://github.com/user-attachments/files/17435601/log.txt)

**Comment by lshqqytiger** [comment]
Do you have any model file at models/Stable-diffusion folder?

**Comment by BlindTheBoundDemon** [comment]
No model so far, but i do have one downloaded I intend to add

**Comment by BlindTheBoundDemon** [comment]
alright, im trying to generate something and the logs are compiling for a while now, which i assume is normal for the first time

**Comment by BlindTheBoundDemon** [comment]
Alright it works amazingly! 8 seconds for a 380x380 image and just around 50 seconds for an upscale
