### ISSUE TITLE
[Bug]: Giving an error with --use.directml

### ISSUE THREAD

**Issue by Bassoopioka** [lshqqytiger/stable-diffusion-webui-amdgpu#567]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Hello i am trying to run Stable Diffusion with my 6700XT. I have a fresh install of Ubuntu 22.04.2 and my specs are Intel 9900k, 32gb ram and amd 6700XT 12gb. I have nothing installed on the ubuntu. I followed the guide given and after installing i use the command: ./webui.sh --use-directml --no-half to start the web UI. But i get the error:
 
ERROR: Could not find a version that satisfies the requirement onnxruntime-directml (from versions: none)
ERROR: No matching distribution found for onnxruntime-directml

But if i launch it with ./webui.sh --use-zluda --no-half it opens the WebUI but only uses my CPU
What am i doing wrong? Or should i install something else? I am a beginner at this stuff so please be patient with me.

### Steps to reproduce the problem

1: install ubuntu 22.04.2
2; open terminal
3: go trough the commands in the guide:

sudo apt install wget git python3 python3-venv libgl1 libglib2.0-0

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.11

git clone https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu

./webui.sh --use-directml --no-half 

4: get the error...

### What should have happened?

WebUi should have opened and used my GPU

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-11-25-03-09.json](https://github.com/user-attachments/files/17896633/sysinfo-2024-11-25-03-09.json)

### Console logs

```Shell
serwu@serwu-Z390-AORUS-MASTER:~/Desktop/Ai/stable-diffusion-webui-amdgpu$ ./webui.sh --use-directml --no-half

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on serwu user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
glibc version is 2.35
Cannot locate TCMalloc. Do you have tcmalloc or google-perftool installed on your system? (improves CPU memory usage)
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
Version: v1.10.1-amd-17-g745b20b7
Commit hash: 745b20b7c69a1fa10ee789b3981484389ac80aef
Installing onnxruntime-directml
Traceback (most recent call last):
  File "/home/serwu/Desktop/Ai/stable-diffusion-webui-amdgpu/launch.py", line 48, in <module>
    main()
  File "/home/serwu/Desktop/Ai/stable-diffusion-webui-amdgpu/launch.py", line 39, in main
    prepare_environment()
  File "/home/serwu/Desktop/Ai/stable-diffusion-webui-amdgpu/modules/launch_utils.py", line 675, in prepare_environment
    run_pip("install onnxruntime-directml", "onnxruntime-directml")
  File "/home/serwu/Desktop/Ai/stable-diffusion-webui-amdgpu/modules/launch_utils.py", line 148, in run_pip
    return run(
  File "/home/serwu/Desktop/Ai/stable-diffusion-webui-amdgpu/modules/launch_utils.py", line 120, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install onnxruntime-directml.
Command: "/home/serwu/Desktop/Ai/stable-diffusion-webui-amdgpu/venv/bin/python" -m pip install onnxruntime-directml --prefer-binary
Error code: 1
stderr: ERROR: Could not find a version that satisfies the requirement onnxruntime-directml (from versions: none)
ERROR: No matching distribution found for onnxruntime-directml
```

**Comment by Bassoopioka** [comment]
I see i didn't realize thank you for clarifying that. Could you direct me to a guide that works on how to get ROCm installed and working with all the steps.

**Comment by lshqqytiger** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs#automatic-installation

**Comment by Bassoopioka** [comment]
Thank you. I did try this and get an: RuntimeError: No HIP GPUs are available. But i will go and make an issue there. I just don't get why this is so hard...
